from app.integrations.gmail import core, ai

GMAIL_TOOLS = {
    # Core tools
    "authenticate_gmail": core.authenticate_gmail,
    "get_emails": core.get_emails,
    "get_email_by_id": core.get_email_by_id,
    "get_unread_emails": core.get_unread_emails,
    "get_starred_emails": core.get_starred_emails,
    "search_emails": core.search_emails,
    "get_emails_by_sender": core.get_emails_by_sender,
    "get_emails_by_label": core.get_emails_by_label,
    "get_emails_by_date_range": core.get_emails_by_date_range,
    "get_email_thread": core.get_email_thread,
    "send_email": core.send_email,
    "send_email_with_attachment": core.send_email,
    "draft_email": core.draft_email,
    "send_draft": core.send_draft,
    "update_draft": core.update_draft,
    "delete_draft": core.delete_draft,
    "reply_email": core.reply_email,
    "reply_all": core.reply_all,
    "forward_email": core.forward_email,
    "list_labels": core.list_labels,
    "add_label": core.add_label,
    "remove_label": core.remove_label,
    "create_label": core.create_label,
    "mark_as_read": core.mark_as_read,
    "mark_as_unread": core.mark_as_unread,
    "star_email": core.star_email,
    "unstar_email": core.unstar_email,
    "archive_email": core.archive_email,
    "unarchive_email": core.unarchive_email,
    "move_to_folder": core.move_to_folder,
    "trash_email": core.trash_email,
    "restore_email": core.restore_email,
    "delete_email": core.delete_email,
    "get_attachments": core.get_attachments,
    "download_attachment": core.download_attachment,
    "save_attachment_to_disk": core.save_attachment_to_disk,
    "schedule_email": core.schedule_email,
    "set_email_reminder": core.set_email_reminder,
    "confirm_action": core.confirm_action,
    "validate_email_address": core.validate_email_address,
    "sanitize_email_content": core.sanitize_email_content,
    "log_email_action": core.log_email_action,
    "audit_email_history": core.audit_email_history,
    "count_emails_by_sender": core.count_emails_by_sender,
    "email_activity_summary": core.email_activity_summary,
    "most_frequent_contacts": core.most_frequent_contacts,
    
    # AI tools
    "summarize_email": ai.summarize_email,
    "summarize_emails": ai.summarize_emails,
    "classify_email": ai.classify_email,
    "detect_urgency": ai.detect_urgency,
    "detect_action_required": ai.detect_action_required,
    "sentiment_analysis": ai.sentiment_analysis,
    "extract_tasks": ai.extract_tasks,
    "extract_dates": ai.extract_dates,
    "extract_contacts": ai.extract_contacts,
    "extract_links": ai.extract_links,
    "draft_reply": ai.draft_reply,
    "generate_followup": ai.generate_followup,
    "auto_reply": ai.auto_reply,
    "rewrite_email": ai.rewrite_email,
    "translate_email": ai.translate_email,
    "auto_label_emails": ai.auto_label_emails,
    "auto_archive_promotions": ai.auto_archive_promotions,
    "auto_reply_rules": ai.auto_reply_rules,
}
